app = "telegram-bot-app"
primary_region = "fra"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PYTHONUNBUFFERED = "1"
  API_TOKEN = "${API_TOKEN}"


[[processes]]
  [processes.worker]
    command = "python bot.py"
